### ISSUE TITLE
Def Server Process: What Concepts?

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/NamingAuthority#142] opened 2021-10-08 12:47 UTC
Continuing on from #138 - 

Is there a definitive list of concepts/types that can be provided via the OGC Def Server?  @ghobona pointed to Section 5.4 of the [OGC-NA Charter](https://portal.ogc.org/files/?artifact_id=77804&version=1), provides us with the following list:

- **Documents**: OGC publications such as standards, engineering reports and best practice documents. These will be registered by OGC staff during the publication process.
- **Namespaces**: A collection of uniquely-assigned identifiers [11].
- **Controlled lists**: A list of terms used to control terminology [2]. This may include codelists.
- **Authority files**: A set of established names or headings and cross-references to the preferred form from variant or alternate forms [2].
- **Ontologies**: A formal specification of concrete or abstract things, and the relationships among them, in a prescribed domain of knowledge (based on the definition in ISO/IEC 19763-1:2015 [4])
- **Alphanumeric classification schemes**: Controlled codes (letters or numbers, or both letters and numbers) that represent concepts or headings [2].
- **Thesauri**: A controlled and structured vocabulary in which concepts are represented by terms, organized so that relationships between concepts are made explicit, and preferred terms are accompanied by lead-in entries for synonyms or quasi-synonyms (based on the ISO definition in ISO 25964-1:2011[5])
- **Normative elements in OGC standards**, according to the provisions of the OGC modular specification policy and the associated name type specification [10]. 

Seems clear, but when we go on to the next step of understanding what technical artifact do we use to submit those definitions this clarity gets a bit lost. @ghobona has provide the following pointer: [Section 7.2 of the OGC-NA Procedures policy](https://docs.opengeospatial.org/pol/09-046r6.html#_submission_process) describes how to submit proposals to the OGC-NA. Here proposers should select a resource type from http://www.opengis.net/def/type, in turn an empty list :(

Also, in the OGC-NA Procedures policy, there is no statement of the form in which the desired content is to be provided. In #138 there are then some statements that can be provided as  `TTL but sometimes RDF/XML. Some of the proposals we received in the past were CSV. Some of the proposals were GML Dictionaries`. These should then be uploaded to GitHub, guess then we wait for a miracle to occur!

I tried to gain a bit of clarity by stepping through the O&M resources (home base), but that got me totally lost - see #140. I'll try and sort the historic confusion in that thread

Back to what (I think) we'd need: `a simple but complete example for guidance in creating the necessary ingestion resources.`

Ideally for each of the types supported by the def server, a simple example of the type of file (ttl, csv, fancy digital napkin!) that would best serve to ingest such a resource - any chance of getting something like this for Christmas???

**Comment by rob-metalinkage** [comment] 2021-10-11 12:33
I recently commented elsewhere about the challenges of having versions in URIs.  The content sources have some details here http://www.opengis.net/def/type/OGC-NA/0/def-type - so the issue is how to tie all these alternative versions together meaningfully.. 

  rdfs:seeAlso <http://www.opengis.net/def/def-type/> ;
  rdfs:seeAlso <http://www.opengis.net/doc/def-names-1> ;
  rdfs:seeAlso <http://www.opengis.net/doc/ogc-na-policies> ;
  owl:sameAs <http://www.opengis.net/def/type/ogc-na/0/def-type> ;
  skos:altLabel "Definition type"@en ;

I'll have to do some digging here to find out what these actually mean in relation to each other and work with Gobe to update a definitive list and put more useful links in place.

**Comment by rob-metalinkage** [comment] 2021-10-15 04:55
NB /def-types/ is actually just a Collection to provide a starting point to other collections of vocabularies organised by  "definition type"   -  

At the very least i shall rename it - its not a registered name so is not needed for stability.

SKOS makes the relation between Collections and  ConceptSchemes a little awkward - it doesnt support heirarchies of ConceptSchemes at all - hence the superposition of hierarchies of Collections spanning multiple ConceptSchemes.

The only solution I can see is to get the UI to expose a common pattern of a top level collection per concept scheme,  and to expose concept scheme metadata for top level collections so they kind of look the same in practice whilst being semantically consistent with the SKOS model.

**Comment by ghobona** [comment] 2023-10-03 12:02
Closing this issue because it has been answered by:

https://github.com/opengeospatial/NamingAuthority/issues/142#issuecomment-938671885

https://github.com/opengeospatial/NamingAuthority/issues/142#issuecomment-941054390

**Closed by ghobona** 2023-10-03 12:02 UTC
Labels: Definitions Server
