### ISSUE TITLE
OMS v3.0 codelists should be registered 

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/NamingAuthority#115] opened 2021-06-11 11:01 UTC
Three concept schemes and included concepts need to be registered to provide vocabularies for the codelists in a joint ISO/TC 211 - OGC Observations, measurements and samples standard (ISO 19156/OGC Abstract Specification Topic 20):

- [CollectionTypeByMemberCharacteristicsSemantics](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/collectionTypeByMemberCharacteristicsSemantics.json)
- [ObservationTypeByResultType](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/observationTypeByResultType.json) and
- [SampleTypeByGeometryType](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/sampleTypeByGeometryType.json)

Each linked file contains a the following in JSON-LD encoding:

- a SKOS ConceptScheme for the classification vocabulary,
- a SKOS Concept for each codelist entry, and 
- a SKOS Collection with all codelist entries as its members

The IDs for the above are created using the following pattern (discussed with @ghobona in [O&M SWG GitHub issue #136](https://github.com/opengeospatial/om-swg/issues/136)):

- classification vocabulary: ```http://www.opengis.net/def/codelist/OGC/0/<codelistName>```
- codelist entry: ```http://www.opengis.net/def/concept/OGC/0/<conceptName>``` and 
- collection: ```http://www.opengis.net/def/codelist/OGC/0/<codelistName>/```

We believe these follow the OGC naming policy naming rule defined in the [Name type specification](https://docs.opengeospatial.org/pol/09-048r5.html#_naming_rule) and the [Definitions Server guidance]~~with the exception of the omitted definition-type for the codelist entry concepts, which we left out as suggested by @ghobona in [his comment on the 4th June](https://github.com/opengeospatial/om-swg/issues/136#issuecomment-854815689)~~.

Note that the codelist entries are also intended to present the concepts they define outside the particular codelist: PointObservation and HomogenousObservationCollection are sub-concepts of Observation and ObservationCollection, and implemented in the OMS v3.0 model using soft-typing via codelist-valued attributes. Thus we feel it is justified to use the URI pattern above for them instead of ```http://www.opengis.net/def/codelist/OGC/0/<codelistName>/<conceptName>```.

We aim to have the ISO 19156 document submitted for the DIS ballot in July, and thus would really welcome a fast-track processing of this issue. We basically need to have the URIs agreed, the implementation on Definitions Server can be done at a more relaxed pace.

**Comment by ghobona** [comment] 2021-06-11 11:22
@ilkkarinne The pattern `http://www.opengis.net/def/OGC/0/<conceptName>` for the codelist entry does not follow the OGC-NA policy, as it is missing a definition type. Apologies if my [June 4th comment](https://github.com/opengeospatial/om-swg/issues/136#issuecomment-854815689) was unclear.

Please attend the OGC-NA session on Thursday, June 17th at 4:30pm - 6:00pm EDT so that you can present the SWG's proposal directly to the OGC-NA.

**Comment by ilkkarinne** [comment] 2021-06-11 12:00
The codelist entry pattern has now been updated to ```http://www.opengis.net/def/concept/OGC/0/<conceptName>```. I could not find a list of the OGC-NA approved definition types, happy to replace the ```concept``` type with a more appropriate one.

Thanks for putting us on the agenda for June 17th on a short notice.

**Comment by nicholascar** [comment] 2021-06-12 03:01
@rob-metalinkage Is this revised URI pattern of `http://www.opengis.net/def/concept/OGC/0/<conceptName>` best practice for the NA? Shouldn't it be something like `http://www.opengis.net/def/<vocabName>/<conceptName>`? 

There is no `http://www.opengis.net/def/concept` object (i.e. no general "concept" vocab).

I would expect the following vocab URIs:

* `http://www.opengis.net/def/CollectionTypeByMemberCharacteristicsSemantics`
    * concepts at `http://www.opengis.net/def/CollectionTypeByMemberCharacteristicsSemantics/<conceptName>`
* `http://www.opengis.net/def/ObservationTypeByResultType`
    * concepts at `http://www.opengis.net/def/ObservationTypeByResultType/<conceptName>`
* `http://www.opengis.net/def/SampleTypeByGeometryType`
    * concepts at `http://www.opengis.net/def/SampleTypeByGeometryType/<conceptName>`

Having stated the above, I suggest implementing simpler URI tokens, perhaps:

* `http://www.opengis.net/def/collection-by-characteristics`
* `http://www.opengis.net/def/observation-by-result`
* `http://www.opengis.net/def/sample-by-geometry`

Further, I see no reason, with the current NA vocab system, for the `/OGC/0/` elements of the URIs although they could be preserved if there really is a need to maintain that versioning style. But I'd discourage it and recommend seeing the vocab & concept metadata for versioning, not the URI.

**Comment by ghobona** [comment] 2021-06-12 08:11
@nicholascar We have a [policy](https://docs.opengeospatial.org/pol/09-048r5.html) in place, approved by the TC on 2018-09-05. There are a number of [proposals](https://github.com/opengeospatial/NamingAuthority/issues?q=is%3Aopen+is%3Aissue+label%3Apolicy) for updates to the policy. If you are proposing a change to the policy, I recommend creating a separate GitHub issue so that the discussion can be tracked more easily.

**Comment by ilkkarinne** [comment] 2021-06-14 16:51
Just for the record, the URI structure suggested by @nicholascar is close to what the O&M SWG originally had in mind and would prefer if there was no policy against it.

**Comment by rob-metalinkage** [comment] 2021-06-15 00:26
From the perspective of the infrastructure we need to be agnostic because we have both patterns in play..

However, the general principle is that URI paths represent governance domains - they are the only mechanism to allow the Naming Authority to delegate to a working group the tasks segment a register into sub-registers as required.

The implication is that each element of the path needs a description and a reason for being that makes sense to a reader. 

So a couple of antipatterns here I can call out

/concept/ as a top-level register doesnt work - its actually a duplicate of /def/ - everything under /def/ is a concept or container of concepts that can be modelled as a SKOS concept, conceptscheme or collection.

/OGC/ implies that it is expected that other authorities can also define such things - this is fine however IMHO this means that the governance context for such a decision needs to be identified at the level above.   This could be a generic naming and governance policy which could be managed by the NA - without it we'll have a lot of messy similar explanations proliferating at this level...

/0/ - as per last option, the notion and mechanisms for versioning need to be very clearly expressed. This may in fact be easier with separate versions called out, but it adds a lot of complexity and needs to be supported by descriptions of what this register is.

/codelist/ - this also raises questions - often a "code" in one domain is a fully modelled class in another domain (soft-vs hard typing) - IMHO its better to understand the governance of the concept and leave it open how its modelled. (plan B would be a canonical pattern to link codelists with model representations - this is an IE or testbed activity I suspect to gather experience and consensus around the best way)

The big question for the infrastructure is the "unit of governance" 

/def/<register> implies a skos:ConceptScheme for <register> but that doesnt stop the definition of ConceptSchemes at lower levels, because there is no requirement a register item (next level in path) is a Concept - it could be a subregister.  So if you add paths you should define a the relevant ConceptSchemes and metadata about the purpose of each one.

(and yes this logic needs to be retrofitted to the definitions server - and this is still only my view after spending quite a while trying to work with the content available and implement some decent defaults.)

**Comment by ilkkarinne** [comment] 2021-06-15 06:33
Ok, thanks @rob-metalinkage, this helps. based on this we would like to revise the proposal to use the following patterns:
Three classification ConceptSchemes to register:

- ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type```
- ```http://www.opengis.net/def/observation-collection-type/OGC/0/by-member-characteristics-semantics``` and
- ```http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type```

the entries (concepts) under each scheme would follow the pattern: ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/category-observation```

BTW is ```CamelCase``` or ```kebab-case```preferred here?

**Comment by ilkkarinne** [comment] 2021-06-15 10:47
I have now revised the OMS Observation, ObservationCollection and Sample classification concepts a follows:

Three top-level classification ConceptSchemes:

- [Observation type](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/observationType.json), ```http://www.opengis.net/def/observation-type```,
- [ObservationCollection type](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/observationCollectionType.json) ```http://www.opengis.net/def/observation-collection-type``` and
- [Sample type](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/sampleType.json) ```http://www.opengis.net/def/sample-type```

Of these the first already exists in the Definitions Server, but need fixing (more about that at the end).

Three particular classification sub-ConceptSchemes defined in the OMS v3.0 specification:
- [Observation type by result type](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/observationTypeByResultType.json), ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type```,
- [ObservationCollection type by the semantic interpretation of the memberCharacteristics](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/collectionTypeByMemberCharacteristicsSemantics.json), ```http://www.opengis.net/def/observation-collection-type/OGC/0/by-member-characteristics-semantics```, and
- [SpatialSample type by the geometry type of the shape attribute](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/sampleTypeByGeometryType.json) ```http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type```

Concepts/ConceptSchemes to register by classification scheme:
- Under ```http://www.opengis.net/def/observation-type```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type```
- Under ```http://www.opengis.net/def/observation-collection-type```
   - ```http://www.opengis.net/def/observation-collection-type/OGC/0/by-member-characteristics-semantics```
- Under ```http://www.opengis.net/def/sample-type```
   - ```http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type```
- Under ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type```
   - ``` http://www.opengis.net/def/observation-type/OGC/0/by-result-type/observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/measurement```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/category-observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/truth-observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/count-observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/temporal-observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/geometry-observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/complex-observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/discrete-coverage-observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/discrete-point-coverage-observation```
   - ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type/time-series-observation```
- Under ```http://www.opengis.net/def/observation-collection-type/OGC/0/by-member-characteristics-semantics```
   -  ```http://www.opengis.net/def/concept/OGC/0/SummarizingObservationCollection```
   -  ```http://www.opengis.net/def/concept/OGC/0/HomogenousObservationCollection```
- Under  ```http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type```
   - ```http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type/point```
   - ```http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type/curve```
   - ```http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type/surface```
   - ```http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type/solid```
 
Happy to loose the ```/OGC/0``` part, but if required by the current policy then I guess nothing we (O&M SWG) can do within the target end-of-July 2021 submission timeframe.

Regarding the [http://www.opengis.net/def/observation-type](http://www.opengis.net/def/observation-type/): the current Def.server seems to have two members under in, both ConceptSchemes themselves: 
- [Observations and Measurements definitions](http://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/ogc-om/) ```http://www.opengis.net/def/ogc-om``` and [Observations and Measurements XML definitions
](http://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/ogc-omxml/) ```http://www.opengis.net/def/ogc-omxml```. IFAK these are not sub-classifications of ```observation-type```, but  lists of various definitions picked from the specification documents for the older version of O&M abstract specification and it's XML Implementation. They do have the Observation classifications too, but are mixed with other things too, such as SamplingFeature classifications.

The proposed fixed: remove the  ```http://www.opengis.net/def/ogc-om``` member from the SKOSCollection ```http://www.opengis.net/def/observation-type/``` but keep the ```http://www.opengis.net/def/ogc-omxml``` with the new ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type```

**Comment by nicholascar** [comment] 2021-06-15 11:41
Hi all, sorry but I don;t think, and I don't get from Rob's post above, that including `/OGC/0/` in the URIs is a good idea. I see that both URIs with (`www.opengis.net/def/crs/EPSG/0/3163`) and URIs without (`http://www.opengis.net/register/ogc-na/authority`) those path segments are in use, so clearly there's no "one way to do it". 

I agree with most of the current policy, however experience with PID management in several regimes has shown me that identifiers are best structured as "flat" as possible, i.e. with few path segments, so I prefer the policy's simple implementation of the pattern `"http://www.opengis.net/" OGCResource "/" ResourceSpecificPath` with URIs like `https://www.opengis.net/def/dggs/code/celledgetype`.

This is because we can easily, and best should treat the URIs as Primary Keys that really just differentiate all the resources in our control (i.e. all those in the top-level namespace, here `www.opengis.net`) and then use data and systems, not identifiers, to describe them, including specific ownership, management, versions etc.

Complex URIs are hard to manage and duplicate data/metadata.

We have nice tools to redirect things anywhere too, such as the NA's new vocab server, so we can 'affords' to create simple URIs.

So YES to all the URIs above with `/OGC/0/` removed!

**Comment by ghobona** [comment] 2021-06-15 11:59
@ilkkarinne The revised versioned URIs in https://github.com/opengeospatial/NamingAuthority/issues/115#issuecomment-861395397 look fine.

Regarding the proposal to remove `http://www.opengis.net/def/ogc-om`, we have to assume that there are applications that make use of that URI and therefore it is not possible to remove it. The URI can however be deprecated if the O&M SWG passes a Motion recommending that the OGC-NA does so.

Regarding versioning of URIs, it is policy and the timeframe of end of July 2021 is not sufficient time to consult on a revision of the policy.

**Comment by ilkkarinne** [comment] 2021-06-15 12:12
Thanks for clarifications @ghobona.

I would not want to remove the ```http://www.opengis.net/def/ogc-om``` concept scheme itself, just edit the members of the ```http://www.opengis.net/def/observation-type/``` so that the ```http://www.opengis.net/def/ogc-om``` would no longer be a member of that collection.

To the O&M SWG this is considered an error, since it seems to suggest that SamplingFeatures and Specimen are also Observation sub-types, when they are in fact other concepts defined in the O&M v2.0 specification.

**Comment by ghobona** [comment] 2021-06-15 16:00
@ilkkarinne Ok, please put the proposal (i.e. edit the members of the `http://www.opengis.net/def/observation-type/`) forward during your presentation to the OGC-NA. We will still need the O&M SWG to endorse the proposal but that can be done after the OGC-NA session.

**Comment by rob-metalinkage** [comment] 2021-06-17 03:55
@ilkkarinne - can you also make sure you add to the proposal the mechanisms to go from the normative artefacts to the URI and the details it should resolve to.  

If this is "hand built" then please indicate if that is because:
a) tools and practices to automate not available
b) information required to perform the mapping not available in the artefacts 
c) pattern (in input or output) is not consistent enough to describe rules to automate 
d) activity SWG is happy to repeat manually as often as required

I think we should be seeking to establish a best practice here and set up infrastructure tooling to support - and I am willing to support such an activity. (We are setting up python based git-hub workflows to support transformations of normative resources to canonical forms and pre-publication validation)

**Comment by ilkkarinne** [comment] 2021-06-17 20:23
Hi @rob-metalinkage. If I understand your request correctly, the answer is d): The concepts described as code items here do not have a corresponding normative artefacts at all in the revised ISO 19156 specification. The Observation and Sample specialization was done by specialized UML classes in O&M v2.0, but in OMS v3.0 they have been replaced by a more generic classification mechanisms based on classification schemes defined as codelists.

Thus the three proposed OMS codelists are to be the definitive source for these classification schemes, and it's not expected that there will be changes to these after the standard is finalized. However it is expected that there will be other classification schemes for Observations, Samples and perhaps also ObservationCollections, that may need to be added in the OGC Definitions Server in the future. Some of these may originate from the O&M SWG activity, but some may also come from outside OGC. Thus I feel that it may be a good thing to include the "OGC" authority URI part to distinguish the classification schemes governed by the OGC O&M SWG from the ones originating from other sources.

**Comment by ghobona** [comment] 2021-06-17 22:00
2021-06-17 OGC-NA session approved the 2 proposals from the O&M SWG.

**Comment by ilkkarinne** [comment] 2021-06-18 05:01
Thanks. Regarding details of the rest of the registration process @ghobona and @rob-metalinkage:

1. Should the URI be using ```lowerCamelCase``` or ```kebab-case``` (current format)? 
2. I understood that you will provide a TTL for the O&M SWG final review. Is the SKOS format content at https://github.com/opengeospatial/om-swg/tree/master/oms-abstract-spec/codelists sufficient, or do we need to provide something else?
3. How soon can be consider the URIs to be fixed, so we can make the required edits to the specification and the UML model?

**Comment by rob-metalinkage** [comment] 2021-06-18 06:06
1 - this is something we should address - I have created an issue #116  for the general case - please inform requirements for your SWG 

2 - the JSON there is _close_  - if it was valid JSON-LD it should be serialisable as TTL - please use the JSON-LD playground or similar - here is your data with a couple of edits to show the sort of tweaks we need: https://tinyurl.com/34szazwm  
(if you have evidence that is a valid JSON-LD form of RDF then need to explain why - I'm not 100% sure I am up-to-date with the changes in JSON-LD world :-) )

3. I think the URIs are now "fixed"   

to fix the collections content we also need to update https://github.com/opengeospatial/NamingAuthority/blob/master/definitions/conceptschemes/om.ttl

Can we set up a meeting to do this collaboratively - I looked and  removing the feature types from the collection still leaves the features types in a concept scheme called "ObservationType" - do we want to refactor into two concept schemes 

While we are at it I think we should address your requirements for all the alternative Case versions (camel and upper/lower cases) 

<http://www.opengis.net/def/observation-type/ogc-om   owl:sameAs <http://www.opengis.net/def/observationType/OGC-OM> .

(maybe we can mark all as deprecated and O&M 3 can be clean - or perhaps it was always a bad idea :-)

**Comment by ilkkarinne** [comment] 2021-06-18 06:31
@rob-metalinkage: I trust your validation and expertise on JSON-LD and RDF, however your tinyurl resolves into a blank JSON-LD playground, could you create a pull request of the tweaked content in the O&m SWG GitHub repo master branch at https://github.com/opengeospatial/om-swg/?

**Comment by rob-metalinkage** [comment] 2021-06-18 06:37
oops - all I did was add some "" around "@id" etc and remove some trailing list ,  - not really worth a PR - you can paste the content in and try it...

**Comment by ilkkarinne** [comment] 2021-06-18 07:04
@rob-metalinkage: I must be blind or just not able use the JSON-LD Playground: I don't seem to find find any errors in the files. Could you point out a specific example in one of the files at https://github.com/opengeospatial/om-swg/tree/master/oms-abstract-spec/codelists for me to double-check?

**Comment by KathiSchleidt** [comment] 2021-06-18 12:00
Maybe I'm missing something, but I'm used to JSON-LD files having a context section, couldn't find in the JSON bits

**Comment by ilkkarinne** [comment] 2021-06-18 12:25
Good point @KathiSchleidt, I created these based on the Definitions Server exported entries which had no contexts defined, but instead used the resolved IRIs for the fields, so I ended up using the same syntax:

```json
{
   {
    "@id": "http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type",
    "@type": [
      "http://www.w3.org/2004/02/skos/core#ConceptScheme"
    ],
    "http://www.w3.org/2004/02/skos/core#definition": [
      {
        "@language": "en",
        "@value": "OMS 3.0 SpatialSample classification scheme based on the geometry type of its shape attribute"
      }
    ],
...
}
```
instead of 

```json
{
   {
    "@context": {
         "definition": "http://www.w3.org/2004/02/skos/core#definition"
    }
    "@id": "http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type",
    "@type": [
      "http://www.w3.org/2004/02/skos/core#ConceptScheme"
    ],
    "definition": [
      {
        "@language": "en",
        "@value": "OMS 3.0 SpatialSample classification scheme based on the geometry type of its shape attribute"
      }
    ],
...
}
```

Those wiser in the JSON-LD syntax please advise if this is correct or not

**Comment by rob-metalinkage** [comment] 2021-06-18 22:04
I cleaned out the comments to avoid the confusion caused by my browser incorrectly rendering the JSON - why it thought it was a good idea to strip _some_ of the quotes is beyond me...

We can live with any valid RDF - though life is easier if the Python RDFLib can handle it. It seems fine reading JSON-LD but poor at control over rendering it.

JSON-LD has multiple schema serialisations that are isomorphic ( all resolve to the same RDF. )  

Having good control over these (i.e. forcing JSON-LD for a fixed JSON schema) is something I am keen to explore for the general challenge of semantically enabling APIs. The approach we are looking at is generation of nestable, cachable, modular JSON-LD contexts per specification, and/or per conformance class.  (people keep building flattened overcomplex, changing "big list" approaches like in the early days of software libraries) 

Anyway ... in the absence of authoritative JSON-LD contexts to reference its fair to do your own.

Again - lets touch base in a call and I'll show you some ideas around OGC possibly publishing proxy profiles of SKOS and other needed resources that _do_ have accessible JSON-LD contexts..

**Comment by nicholascar** [comment] 2021-06-20 23:58
> Having good control over these (i.e. forcing JSON-LD for a fixed JSON schema) is something I am keen to explore 

The [RDFlib  JSON-LD plugin](https://github.com/RDFLib/rdflib-jsonld) needs some attention. We need to ensure it's catering for all JSON 1.1 things and then, ideally, we would merge it into the main RDFlib package. 

We would accept work from anyone to specify particular JSON-LD serialization formats! 

Currently RDF/XML has two serialization formats (so called ["XML" & "Pretty XML"](https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/serializers/rdfxml.py#L15)), so JSON-LD could have multiple too.

**Comment by ghobona** [comment] 2021-07-01 10:04
@ilkkarinne Could you please upload all of the RDF/XML or Turtle files for the OMS 3.0 Codelists to the following folder?

https://github.com/opengeospatial/NamingAuthority/tree/master/incubation/ObservationsAndMeasurements/3.0

Once you have uploaded them to the folder, @rob-metalinkage will then process and publish them through the Definitions Server.

**Comment by rob-metalinkage** [comment] 2021-07-05 02:07
Note - I may move them round - I need to work out rules based on the URIs to locate the actual published content so they tend to follow URI directory structures to avoid special case rules...

**Comment by ilkkarinne** [comment] 2021-07-26 11:47
Created a PR to add the OMS 3.0 codelists under incubation, ping @ghobona and @rob-metalinkage

**Comment by ghobona** [comment] 2021-09-06 16:40
@ilkkarinne I have just published the OMS 3.0 codelists on the Definitions Server.

Please review. There are some Collection instances that do not appear to be linked to their Concept instances.

Cc: @rob-metalinkage

**Comment by KathiSchleidt** [comment] 2021-09-06 19:51
@ghobona under which of the many O&M versions currently there (and causing confusion?)
From what I see at http://defs.opengis.net/vocprez/object?uri=http://www.opengis.net/def/observationType/ it's still all various V2 versions
:?

**Comment by ghobona** [comment] 2021-09-07 06:24
@KathiSchleidt We uploaded the RDF from https://github.com/opengeospatial/NamingAuthority/tree/master/incubation/ObservationsAndMeasurements/3.0/codelists

They were provided by @ilkkarinne

**Comment by ilkkarinne** [comment] 2021-09-08 06:47
Hi @ghobona (@rob-metalinkage), thanks for adding the OMS 3.0 codelists as per the first O&M SWG proposal approved in the 2021-06-17 OGC-NA session. The only issue I see is that the all of the exact match items seem to be duplicated for the code list items. Example: http://www.opengis.net/def/sample-type/OGC/0/by-geometry-type/surface has six exact match links three of which are duplicates, in contrast to the [JSON-LD](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/ObservationsAndMeasurements/3.0/codelists/sampleTypeByGeometryType.json#L146) or [TTL](https://github.com/opengeospatial/NamingAuthority/blob/master/incubation/ObservationsAndMeasurements/3.0/codelists/ttl/sampleTypeByGeometryType.ttl#L38) versions which only has the correct three exact match links.

Considering your note on some Collection instances that do not appear to be linked to their Concept instances, could you please be more specific, and also if the O&M SWG or OGC staff (@rob-metalinkage?) are expected to react? As far as I recall Rob noted that we do not have to provide these links on the JSON-LD input, but it's also fine if we do, and the missing bits will be added it the preparation process by the OGC staff.

The second approved in the 2021-06-17 OGC-NA session "Fix for the Observation type scheme" is only carried out half-way as far as I can tell (linked to the confusion mentioned by @KathiSchleidt): the new OMS 3.0 ```http://www.opengis.net/def/observation-type/OGC/0/by-result-type``` was added to the collection ```http://www.opengis.net/def/observation-type/``` as requested in "part 2" of the second proposal, but the part 1 (fix): removing the "Observations and Measurements definitions" (http://www.opengis.net/def/ogc-om) from the members of the ```http://www.opengis.net/def/observation-type/``` is not done.

Not sure about how the Definitions server works internally, but I'm guessing that not removing this results in the erroneous listing under the vocabulary [http://www.opengis.net/def/observationType](https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/observationType).

Hoping you are able to also carry out the part 1 of the second proposal as agreed in the 2021-06-17 OGC-NA session as soon as possible.

**Comment by ghobona** [comment] 2021-09-08 11:04
Actions for @ghobona from the Review in https://github.com/opengeospatial/NamingAuthority/issues/115#issuecomment-914966759:

- [ ] Action 1: Remove duplicates of the exact match items. 
- [ ] Action 2: Remove the "Observations and Measurements definitions" collection (http://www.opengis.net/def/ogc-om) from the members of the http://www.opengis.net/def/observation-type/.

**Comment by ghobona** [comment] 2021-10-13 14:54
Thanks @ilkkarinne for reporting about the "Input Error" 400 issue. I have taken an action to fix http://www.opengis.net/def/observation-collection-type/OGC/0/by-member-characteristics-semantics

**Comment by ghobona** [comment] 2021-11-30 07:45
Closing this Issue because Item Registration has been completed. The remaining issue (re: Action 1) appears to be caused by the User Interface and therefore will be discussed in a [separate Issue](https://github.com/opengeospatial/NamingAuthority/issues/156).

**Closed by ghobona** 2021-11-30 07:45 UTC
Labels: Item Registration
