### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by marqh** [opengeospatial/NamingAuthority#124] opened 2021-06-29 08:31 UTC
Related to #123 but with some different nuance

i am struggling with content negotiation with the OGC registry

I expect 
```
wget --header 'Accept:text/ttl' -O bald.ttl https://www.opengis.net/def/binary-array-ld
```
to return the turtle encoded Owl Ontology 
this currently works using a hard coded redirect, as described in #123 

i also expect this pattern to work for individual resources.
So, while
```
wget --header 'Accept:text/html' -O Reference.html https://www.opengis.net/def/binary-array-ld/Reference
```
successfully resolves to the html web page
I would expect 
```
wget --header 'Accept:text/ttl' -O Reference.ttl https://www.opengis.net/def/binary-array-ld/Reference
```
to return the Owl definition of the `owl:Class` `bald:Reference`

but no, i get an `ERROR 404: Not Found' response

this is surprising and concerning

more experimentation unearths the pattern
```
wget --header 'Accept:text/turtle' -O Reference.ttl http://defs.opengis.net/vocprez/object?uri=https%3A//www.opengis.net/def/binary-array-ld/Reference
```
but this returns a payload of
```
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
<https://www.opengis.net/def/binary-array-ld/Reference> a skos:Concept ;
    skos:broader <https://www.opengis.net/def/binary-array-ld/Resource> ;
    skos:definition "Reference"@en ;
    skos:prefLabel "Reference"@en .
```

This is also unexpected.  The resource `https://www.opengis.net/def/binary-array-ld/Reference` is defined within `https://www.opengis.net/def/binary-array-ld` as
```
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix dct:   <http://purl.org/dc/terms/> .
<https://www.opengis.net/def/binary-array-ld/Reference>
        a                owl:Class ;
        rdfs:label       "Reference" ;
        rdfs:subClassOf  <https://www.opengis.net/def/binary-array-ld/Resource> ;
        dct:description  "The definition of a reference from one Array to another." .
```
but I don't seem to be able to return this payload from the definitions server

Please may you help / advise on this behaviour and whether the requirement from me is clear?

thank you
mark

**Comment by ghobona** [comment] 2021-07-02 17:11
The PR https://github.com/opengeospatial/NamingAuthority/pull/127 adds a section describing the role of Content Negotiation.

**Comment by rob-metalinkage** [comment] 2021-07-06 06:44
requirement is understood...

the wrinkle here is that is not so easy to define how to return an "OWL snippet" - because generally many different pieces of an ontology may refer to a class - such as rdfs:domain and range statements,  statements about the properties of the class etc..

so generally we'll return an entire OWL file or an HTML rendering of OWL file with a fragment identifier etc.

stay tuned - working on this now - I've just completed a flexible automated entailment and SHACL validation environment in python which can be run on the desktop or as a github action - this is because the "whole repository" approach previously available was nearly impossible to debug.   I now have to extend the scope of the processing to the incubation area for models such as this..

**Comment by ghobona** [comment] 2021-07-06 07:36
@rob-metalinkage How about simply running a `DESCRIBE` command on the subject you want to query?

For [example](http://defs.opengis.net:8080/rdf4j-workbench/repositories/ogc-na/query?&query=DESCRIBE%20%3Chttp%3A%2F%2Fwww.opengis.net%2Fdef%2Fsensor-model%2Fcsmwg%2Fcsm%3E&Accept=application%2Frdf%2Bxml), `DESCRIBE <http://www.opengis.net/def/sensor-model/csmwg/csm>` used in a SPARQL query with the Accept parameter set to the relevant media type. 

See the output on the attached screenshot (using Postman).

![Screenshot 2021-07-06 at 08 34 30](https://user-images.githubusercontent.com/18121038/124560782-1b71ae00-de35-11eb-95f0-b0799c24f433.png)

**Comment by dr-shorthair** [comment] 2021-07-06 07:37
https://www.w3.org/Submission/CBD/ was a useful start. I'd add inverse links as well as outbound relations.

**Comment by dr-shorthair** [comment] 2021-07-06 07:38
@ghobona I understand that DESCRIBE is implementation specific.

**Comment by ghobona** [comment] 2021-07-06 07:43
I presume that CBD was submitted to W3C in 2005 and never approved as a W3C Recommendation. Am I right?

**Comment by nicholascar** [comment] 2021-12-10 01:17
The query above demonstrating the deficinecy, `wget --header 'Accept:text/ttl' -O Reference.ttl https://www.opengis.net/def/binary-array-ld/Reference` still returns 404 but now also returns an _Alternate Profiles_ `Link` header payload listing the profiles & formats that are available and the text "A profile for the requested URI base exists but no rules match for the requested format".

[Content Negotiation by Profile](https://w3c.github.io/dx-connegp/connegp/#requestsandresonses) suggests that the server should not respond with _Not Found_ but instead with the default profile/format combo.

I suggest that the ConnegP instructions should be followed but that a note similar to "A profile for the requested URI base exists but no rules match for the requested format" be included in the response. This may clean up some perceptions of the Content Negotiation implementation.

#### CBD
It does appear, from multiple projects not just here, that we generally need a profile defined around the CBD definition which is then all data the system holds centered on the requested object. I expect such a profile is a "fundamental" profile, just as "Container Members" and "Container Annotations" (all info other than member listing) are such profiles. We - OGC and all of us - are missing a catalogue of such fundamental profiles.

**Comment by nicholascar** [comment] 2021-12-10 01:25
The "Container Annotations" fundamental profile is defined: https://w3id.org/profile/contanno. 

I will:
* work with @rob-metalinkage on the "Container Members" profile
* define a test CBD profile
* list all these fundamental profiles (i.e. make the web page https://w3id.org/profile/ work, again)

**Comment by ghobona** [comment] 2022-08-02 17:28
Additional request for Content Negotiation to enable access to JSON and XML representations of Tile Matrix Sets.

https://github.com/opengeospatial/NamingAuthority/issues/106#issuecomment-1183827273

Cc: @jerstlouis

**Comment by rob-metalinkage** [comment] 2023-02-28 10:36
Revisiting the original issue - 

a) text/ttl not supported (its text/turtle) - an elegant response to be provided.
b) we have changed back end processes and now have the full turtle etc available, but exposing these and the redirect to this has not been made available to the production server yet (its using vocprez's limited internal graph view not the source material at the moment)

We'll sort these out.

**Comment by ghobona** [comment] 2023-11-17 18:39
Tested and confirmed to work through Postman.

![Screenshot 2023-11-17 at 18 36 34](https://github.com/opengeospatial/NamingAuthority/assets/18121038/ce26f1bd-66e1-478a-ba74-f9cbf7ed652f)

Closing the GitHub Issue.

**Closed by ghobona** 2023-11-17 18:39 UTC
Labels: Definitions Server
